### ISSUE TITLE
what is the output of this http call?

### ISSUE THREAD

**Issue by greg2git** [mrshah-at-work/fabric-kubernetes#2]
http://YOUR_PUBLIC_IP_HERE:31090/explorer/

i'm assuming it's not this one:
"This site can’t be reached
173.193.85.235 refused to connect."

thx, greg

**Comment by mrshah-at-work** [comment]
Hi @greg2git, can you please use https://ibm-blockchain.github.io .. This repository is outdated.

**Comment by greg2git** [comment]
need to close as my repository got moved.
